import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ThemeRegistry from "@/theme";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import axios from "axios";
import { setupInterceptorsTo } from "@/config/axios";
import { IRANSansX } from "@/config/font";
import "../styles/globals.css";

setupInterceptorsTo(axios);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <body className={IRANSansX.variable}>
        <ReduxProvider>
          <ReactQueryProvider>
            <ThemeRegistry>
              <ThemeProvider options={{ key: "css" }}>
                {children}
              </ThemeProvider>
            </ThemeRegistry>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
